### ISSUE TITLE
Add support for Handoff

### ISSUE THREAD

**Issue by voirol** [johnste/finicky#105]
Thanks for Finicky. I'm finding it super useful with Zoom and Teams links. 

![image](https://user-images.githubusercontent.com/9734252/79063244-f2ff1080-7cd2-11ea-8076-0374a9ecec20.png)

Handoff from iOS to Mac used to respect my default browser setting of Chrome. Since I've installed Finicky, it insists on opening Safari instead of throwing the link to Finicky.

**Comment by johnste** [comment]
Thanks for using Finicky!

I don't have access to an iPhone so I can't test this unfortunately. Maybe you can check if Finicky is picking up the url at all by writing a handler like this and checking the log. https://github.com/johnste/finicky/wiki/Troubleshooting-&-Tips#i-want-to-use-the-sourcebundleidentifier-option-but-i-dont-know-what-bundle-id-to-listen-to

**Comment by voirol** [comment]
Thanks John. 

It appears that for some reason Finicky doesn’t get notified. 

I don’t know enough about it to know why, but here’s the dev doco on handoff: https://developer.apple.com/handoff/

**Comment by johnste** [comment]
Does handoff always start the same browser/app you were using on the phone? So if you browse in Chrome and handoff from your phone, does it start Safari or Chrome (if available) on your mac?

Looking at the docs there it mainly seems like it's meant to handoff between the same app on different platforms. It's hard to tell without being able to test this. https://developer.apple.com/documentation/foundation/task_management/implementing_handoff_in_your_app

**Comment by voirol** [comment]
Hi John

No, it doesn’t. I use Safari on iOS and Chrome on macOS as default browsers and before Finicky, when I had the iPhone on a Safari page, the Chrome icon appeared in the handoff area on the left of the dock. Clicking on it opens the URL in Chrome.

That’s why I find it odd that macOS handoff seems not to respect Finicky as the default browser on macOS, but instead defaults back to Safari. It’s almost as if Finicky isn’t recognised as a “proper” default handler for URLs.

Cheers
Tom

**Comment by bucweat** [comment]
Just a guess but I believe handoff feature is particular to Safari and by this I mean only links opened in Safari are available to be handed off (iOS to Mac and vice versa).

**Comment by voirol** [comment]
> Just a guess but I believe handoff feature is particular to Safari and by this I mean only links opened in Safari are available to be handed off (iOS to Mac and vice versa).

Handoff is not limited to Safari. I have used it between Safari on the iPhone and Chrome on the Mac seamlessly prior to installing Finicky.

Now, Safari on iOS triggers it fine like before, but instead of the Chrome icon popping up on the left of the dock, as it used to, it goes back to the Safari icon and opens Safari if clicked.

**Comment by bucweat** [comment]
OK I learned something new :-) 

After playing around with this some, I have come to some conclusions:
- Opening a link in iOS using Chrome or Safari, the link shows up in MacOS handoff in the MacOS default browser set in System Preferences>General>Default web browser (Safari, Edge, Firefox tested). 
- However, if the default browser is finicky.app then handoff displays Safari icon and link opens in Safari.
 - I added the URL handler mentioned above and it does appear that Finicky is being ignored as there is nothing sent to the Finicky console with handoff, but otherwise it logs events just fine.

Started reading through the Handoff docs shared above, and found the following [here](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Handoff/HandoffFundamentals/HandoffFundamentals.html#//apple_ref/doc/uid/TP40014338)

> Apple apps, such as Safari, Mail, Maps, Contacts, Notes, Calendar, and Reminders use public APIs to implement Handoff for iOS 8 and OS X v10.10. A third-party developer can use the same APIs to implement Handoff in apps that share the developer’s Team ID. **Such apps must either be distributed through the App Store or signed by the registered developer**.

So it sounds like #68 might be necessary before Finicky.app can handle Handoff. But that might just be the beginning as Finicky.app might also have to provide the plumbing to pass the handoff interactions to the browser of choice. This is just a guess, but MacOS must recognize that Finicky.app can not handle handoff interactions, and ends up passing on to Safari to handle it.
