### ISSUE TITLE
Finicky + Browserosaurus

### ISSUE THREAD

**Issue by will-stone** [johnste/finicky#116]
Hi @johnste,

I've just discovered your project and I really like what you've created; writing rules with JS feels very natural to me (and probably many others). I am the author of [Browserosaurus](https://browserosaurus.com), and I can see you've recommended people to look at it in past issues, so thank you very much 😄

I often get requests for a rules engine and I usually point people to Choosy, as I feel this is out-of-scope for my project. However, now that I know about Finicky, I'd much rather point to a fellow open-sourcerer.

So... I was wondering if you'd like a gentleman's agreement to officially endorse each other? After all, you don't want to build a picker and I don't want to build a rules engine (do one thing well and all that). I am more than happy to link to this product on B's website.

Which brings me on to... I think using both Finicky and Browserosaurus could be a great combination. B now has the option to skip being set as the default browser, this means Finicky could be default and people can write rules to open with Browserosaurus, or fallback to it. 

I've given this a go and it seems to be working well: 

```js
module.exports = {
  defaultBrowser: "Browserosaurus",
  handlers: [
    {
      match: finicky.matchHostnames(["apple.com"]),
      browser: "Safari",
    },
  ],
};
```

There's only one issue I've found and that's with using the `open` command from the Terminal. When I run `open "http://example.com"`, F sends it to B but a `blur` event is also triggered and so B shows and immediately closes again. I'm wondering if Finicky is triggering this some how? Does it alter window focus? Or maybe it's a macOS bug with window focus changing so rapidly.

Look forward to hearing your thoughts on cooperation,

Will.

**Comment by johnste** [comment]
Hey Will, nice to hear from you! 

I've definitely been aware of Browserosaurus for quite some time now, and I think it's a great tool.

I do agree with the statement that Finicky has always been about rule based Browser selection rather than showing some graphical user interface, and while I can't guarantee that that will never happen I think it's very unlikely.

I'm completely up for for endorsing Browserosaurus as an alternative whenever Finicky isn't the best fit for someone. Finicky doesn't really have a website other than the GitHub repo, but I could for example add a section in the readme suggesting it as an alternative. I can a pull request to Finicky and let you give feedback on it.

Also happy to hear you trying out combining both tools! Finicky shouldn't blur or open any browser in the background unless explicitly told so so not sure what's going on there. I'll give it a shot when I have some time.

/John

**Comment by johnste** [comment]
I went ahead and added a [link in the readme](https://github.com/johnste/finicky/blob/master/README.md#alternatives), do you think this is ok?

**Comment by will-stone** [comment]
Nice. I've added Finicky to the [FAQ section](https://browserosaurus.com/#faq) of B's website, under "I would like to open a particular browser automatically for specific URLs".

**Comment by johnste** [comment]
I haven't been able to reproduce the blur issue you experienced using Browserosaurus with Finicky, either as the default browser or as using it specifically for some urls.

**Comment by will-stone** [comment]
Interesting. And to confirm, that's when you open a URL from the Terminal?

**Comment by johnste** [comment]
Yeah, I just ran `> open http://example.com` (even tried with and without surrounding quotation marks). I'm using iterm2 on Catalina.

**Comment by will-stone** [comment]
Yeah my setup is the same 🤔 how strange. I’ll have more of a play on my end, but it sounds like a problem with my machine.

Right, glad we had this chat, I hope we manage to make others more aware of each other’s products 😊

**Comment by faisal3389** [comment]
Hi guys, 

I know this issue is closed but can you point me to the right way to use both products in tandem.

I have set finicky as the default browser and within `~/.finicky.js` I have added   `defaultBrowser: "Browserosaurus"` but was unable to get Browserosaurus to open up for an URL not defined in other rules. Is there anything else that needs to be set?

TIA. 
PS: love both products was looking for something like this for long time, glad i found these.
