### ISSUE TITLE
Finicky opens extra New Window when opening link

### ISSUE THREAD

**Issue by shahrviral** [johnste/finicky#150]
Whenever Finicky opens a new browser from scratch when a link is clicked it will open an extra window to that browser, This issue is reproducible every time. I don't think this is related to the  3.1.3 release as I have noticed this before as well. Not sure if its happening for anyone else...

**Comment by johnste** [comment]
I don't think I have noticed this behavior. Do you mean it happens when Finicky isn't running?

**Comment by shahrviral** [comment]
When the browser is not running. I am attaching a video to explain what I am seeing. I think that old issue with it incorrectly opening is also still there 

[2020-11-22 at 11.59.50.mp4.zip](https://github.com/johnste/finicky/files/5580229/2020-11-22.at.11.59.50.mp4.zip)

**Comment by shahrviral** [comment]
It might be related to the detect running browsers #145 , I am not sure

**Comment by alejandroivan** [comment]
This always happens when you have "save opened tabs" in Chrome preferences, even without Finicky in the middle.
What you could do is to try to add the `--parent-window` parameter to the executable, so it uses the already opened window instead of creating a new one.

Take for example, this terminal command opens a new window:
`open -a "Google Chrome" https://www.google.com`

But this doesn't:
`open -a "Google Chrome" --args --parent-window https://www.google.com`

Way to reproduce it? Enable "remember opened tabs", open 2 different websites and close Chrome with Cmd+Q. Then type the command in the Terminal app.

**Comment by shahrviral** [comment]
This is an issue with Firefox and not Finicky. Sorry

**Comment by shahrviral** [comment]
@alejandroivan I'll try to see if there is a config in Firefox which is causing this
