### ISSUE TITLE
Regex matcher is not working

### ISSUE THREAD

**Issue by kirillzh** [johnste/finicky#66]
Regex matchers don't seem to be working. I have this simple config:
```js
module.exports = {
  defaultBrowser: "Firefox",
  handlers: [{
    match: "/http:\/\/example\.com/",
    browser: "Google Chrome"
  }]
};
```
In this example I'm expecting `http://example.com` to be open in Google Chrome but it opens in Firefox (both in console URL tester as well as when actually trying to open the link). I also tried different regex pattern `/http:\\/\\/example\\.com/` which I took from [ConfigHandlers.swift](https://github.com/johnste/finicky/blob/8dc481c62157e3b22dd899fd3ac0796ddfd207b5/Finicky/FinickyTests/ConfigHandlers.swift#L28) tests but that pattern is not working either, it doesn't look like correct pattern anyway ([test](https://regex101.com/r/6fWx3r/1)).

macOS: 10.14.5
Finicky version: v2.1.0 (136)

**Comment by johnste** [comment]
Hey Kirill!

The regex matcher expects an instance of RegExp in JavaScript, that is, you don't want to wrap it in a string. The example in ConfigHandlers is using a string to generate an example configuration which is why it might be misleading.


Your config should work with this:
```
matcher: /http:\/\/example\.com/,
```

Let me know if this helps!

**Comment by kirillzh** [comment]
Thanks, @johnste! That works 😊
