### ISSUE TITLE
Rename API method matchDomains to matchHostnames

### ISSUE THREAD

**Issue by exalted** [johnste/finicky#73]
Hi,

My :two-cents: here: I think `finicky.matchDomains` is a misleading name choice for an API that would actually match the entire hostname instead.

I am telling this, because I was trying the simplest configuration:

```
module.exports = {
  defaultBrowser: 'Safari',
  handlers: [
    {
      match: finicky.matchDomains([ 'example.com' ]),
      browser: 'Firefox'
    }
  ]
};
```

But it kept failing to open http://www.example.com/ with Firefox. I realized it wasn't matching the URL because of the `www` (subdomain) in the hostname.

Anyway changing matcher to `finicky.matchDomains([ /(.+\.)?example.com/ ])` did the trick.

**Comment by johnste** [comment]
Hey, thanks for the feedback!

I completely agree, I think when naming it I didn't really consider the difference between hostnames and domains and picked domains because it felt like a term more people would understand.

I don't want to change the behavior of the function though, but I can certainly add an alias called `matchHostname` and change the documentation to always refer to that name. At some point later I might deprecate the `matchDomains` completely and provide another utility function with that functionality.

**Comment by exalted** [comment]
Whatever you think is best. Thank you!

**Comment by johnste** [comment]
Release in https://github.com/johnste/finicky/releases/tag/v2.2.1

**Comment by ProLoser** [comment]
So umm... how would you go about create a `matchDomain` like behavior? Like allowing any subdomain of a top (or arbitrary level) domain. Just a function that manually checks for a subset of the hostname?
